version: '3.8'

services:
  # Databases
  postgres:
    image: postgres:15-alpine
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-net

  mongodb:
    image: mongo:6.0
    container_name: library_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: catalog_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - library-net

  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: library_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # AMQP protocol
      - "15672:15672"   # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - library-net

  # Microservices
  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    container_name: library_catalog_service
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://admin:adminpassword@mongodb:27017/catalog_db?authSource=admin
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - library-net

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: library_auth_service
    restart: always
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - POSTGRES_URI=postgres://postgres:adminpassword@postgres:5432/library_db
      - JWT_SECRET=super_secret_library_key_123
    depends_on:
      - postgres
    networks:
      - library-net

  circulation-service:
    build:
      context: ./circulation-service
      dockerfile: Dockerfile
    container_name: library_circulation_service
    restart: always
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://admin:adminpassword@mongodb:27017/circulation_db?authSource=admin
      - JWT_SECRET=super_secret_library_key_123
    depends_on:
      - mongodb
    networks:
      - library-net

volumes:
  postgres_data:
  mongodb_data:
  rabbitmq_data:

networks:
  library-net:
    driver: bridge
